name: Latest liblab updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *' # 11am UTC corresponds to 5am CST

jobs:
  generate-sdks-and-publish-prs:
    name: Generate SDKs and publish PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SDKs and publish PRs
        uses: liblaber/liblab-sdk-updates@v1
        with:
          liblab_token: ${{ secrets.LIBLAB_TOKEN }}
          github_token: ${{ secrets.LIBLAB_GITHUB_TOKEN }}
